# Generated by OpenAPI Generator: https://openapi-generator.tech
# Do not edit this file manually - it will be overwritten during regeneration

# Add the generated lib directory to the load path
# Try multiple path resolution strategies for different contexts (development vs gem)
generated_lib_paths = [
  File.expand_path('generated/lib', __dir__),  # Development path
  File.expand_path('generated/lib', File.dirname(__FILE__)),  # From current file directory
  File.expand_path('../compute/generated/lib', __dir__),  # Alternative relative path  
  File.expand_path('../../../../compute/generated/lib', __FILE__)  # From gem context
]

# Debug: print attempted paths in development mode
if ENV['ERYPH_DEBUG'] || $DEBUG
  puts "DEBUG: Attempting to find generated client in:"
  generated_lib_paths.each_with_index do |path, i|
    exists = File.exist?(path)
    puts "  #{i+1}. #{path} (exists: #{exists})"
  end
end

generated_lib_path = generated_lib_paths.find { |path| File.exist?(path) }

if generated_lib_path
  $LOAD_PATH.unshift(generated_lib_path) unless $LOAD_PATH.include?(generated_lib_path)
  
  begin
    require 'compute_client'
  rescue LoadError => e
    # More detailed error in debug mode
    error_msg = "Failed to load compute_client from #{generated_lib_path}: #{e.message}"
    if ENV['ERYPH_DEBUG'] || $DEBUG
      error_msg += "\nLoad path: #{$LOAD_PATH.join(':')}"
      error_msg += "\nFiles in #{generated_lib_path}: #{Dir.entries(generated_lib_path).join(', ')}" if File.exist?(generated_lib_path)
    end
    raise LoadError, "#{error_msg}. Please run generate.rb to regenerate the client."
  end
else
  raise LoadError, "Generated compute client directory not found in any of: #{generated_lib_paths.join(', ')}. Please run generate.rb to regenerate the client."
end

module Eryph
  # Create ComputeClient namespace that mirrors the generated ComputeClient module
  module ComputeClient
    # Re-export all core classes
    ApiClient = ::ComputeClient::ApiClient
    Configuration = ::ComputeClient::Configuration
    ApiError = ::ComputeClient::ApiError
    
    # Re-export all API endpoint classes
    CatletsApi = ::ComputeClient::CatletsApi
    GenesApi = ::ComputeClient::GenesApi
    OperationsApi = ::ComputeClient::OperationsApi
    ProjectMembersApi = ::ComputeClient::ProjectMembersApi
    ProjectsApi = ::ComputeClient::ProjectsApi
    VersionApi = ::ComputeClient::VersionApi
    VirtualDisksApi = ::ComputeClient::VirtualDisksApi
    VirtualNetworksApi = ::ComputeClient::VirtualNetworksApi
    
    # Re-export all model classes  
    ApiVersion = ::ComputeClient::ApiVersion
    ApiVersionResponse = ::ComputeClient::ApiVersionResponse
    Catlet = ::ComputeClient::Catlet
    CatletConfigOperationResult = ::ComputeClient::CatletConfigOperationResult
    CatletConfigValidationResult = ::ComputeClient::CatletConfigValidationResult
    CatletConfiguration = ::ComputeClient::CatletConfiguration
    CatletDrive = ::ComputeClient::CatletDrive
    CatletDriveType = ::ComputeClient::CatletDriveType
    CatletList = ::ComputeClient::CatletList
    CatletNetwork = ::ComputeClient::CatletNetwork
    CatletNetworkAdapter = ::ComputeClient::CatletNetworkAdapter
    CatletStatus = ::ComputeClient::CatletStatus
    CatletStopMode = ::ComputeClient::CatletStopMode
    DiskStatus = ::ComputeClient::DiskStatus
    ExpandCatletConfigRequestBody = ::ComputeClient::ExpandCatletConfigRequestBody
    ExpandNewCatletConfigRequest = ::ComputeClient::ExpandNewCatletConfigRequest
    FloatingNetworkPort = ::ComputeClient::FloatingNetworkPort
    Gene = ::ComputeClient::Gene
    GeneList = ::ComputeClient::GeneList
    GeneType = ::ComputeClient::GeneType
    GeneWithUsage = ::ComputeClient::GeneWithUsage
    NewCatletRequest = ::ComputeClient::NewCatletRequest
    NewProjectMemberBody = ::ComputeClient::NewProjectMemberBody
    NewProjectRequest = ::ComputeClient::NewProjectRequest
    NewVirtualDiskRequest = ::ComputeClient::NewVirtualDiskRequest
    Operation = ::ComputeClient::Operation
    OperationList = ::ComputeClient::OperationList
    OperationLogEntry = ::ComputeClient::OperationLogEntry
    OperationResource = ::ComputeClient::OperationResource
    OperationResult = ::ComputeClient::OperationResult
    OperationStatus = ::ComputeClient::OperationStatus
    OperationTask = ::ComputeClient::OperationTask
    OperationTaskReference = ::ComputeClient::OperationTaskReference
    OperationTaskStatus = ::ComputeClient::OperationTaskStatus
    PopulateCatletConfigVariablesRequest = ::ComputeClient::PopulateCatletConfigVariablesRequest
    ProblemDetails = ::ComputeClient::ProblemDetails
    Project = ::ComputeClient::Project
    ProjectList = ::ComputeClient::ProjectList
    ProjectMemberRole = ::ComputeClient::ProjectMemberRole
    ProjectMemberRoleList = ::ComputeClient::ProjectMemberRoleList
    ResourceType = ::ComputeClient::ResourceType
    StopCatletRequestBody = ::ComputeClient::StopCatletRequestBody
    TaskReferenceType = ::ComputeClient::TaskReferenceType
    UpdateCatletRequestBody = ::ComputeClient::UpdateCatletRequestBody
    UpdateProjectNetworksRequestBody = ::ComputeClient::UpdateProjectNetworksRequestBody
    ValidateConfigRequest = ::ComputeClient::ValidateConfigRequest
    ValidationIssue = ::ComputeClient::ValidationIssue
    VirtualDisk = ::ComputeClient::VirtualDisk
    VirtualDiskAttachedCatlet = ::ComputeClient::VirtualDiskAttachedCatlet
    VirtualDiskGeneInfo = ::ComputeClient::VirtualDiskGeneInfo
    VirtualDiskList = ::ComputeClient::VirtualDiskList
    VirtualNetwork = ::ComputeClient::VirtualNetwork
    VirtualNetworkConfiguration = ::ComputeClient::VirtualNetworkConfiguration
    VirtualNetworkList = ::ComputeClient::VirtualNetworkList
  end
  
  # Keep the old Generated namespace for backward compatibility
  module Generated
    # Alias the main classes for backward compatibility
    NewCatletRequest = ::ComputeClient::NewCatletRequest
    StopCatletRequestBody = ::ComputeClient::StopCatletRequestBody
    CatletStopMode = ::ComputeClient::CatletStopMode
    ApiClient = ::ComputeClient::ApiClient
    Configuration = ::ComputeClient::Configuration
  end
  
  module Compute
    module Generated
      # Re-export the generated client classes for easier access
      Client = ::ComputeClient
    end
  end
end
