# Generated by OpenAPI Generator: https://openapi-generator.tech
# Do not edit this file manually - it will be overwritten during regeneration

# Add the generated lib directory to the load path
$LOAD_PATH.unshift(File.expand_path('generated/lib', __dir__))

require 'compute_client'

module Eryph
  # Create ComputeClient namespace that mirrors the generated ComputeClient module
  module ComputeClient
    # Re-export all API classes
    ApiClient = ::ComputeClient::ApiClient
    Configuration = ::ComputeClient::Configuration
    ApiError = ::ComputeClient::ApiError
    
    # Re-export all API endpoint classes
    CatletsApi = ::ComputeClient::CatletsApi
    GenesApi = ::ComputeClient::GenesApi
    OperationsApi = ::ComputeClient::OperationsApi  
    ProjectMembersApi = ::ComputeClient::ProjectMembersApi
    ProjectsApi = ::ComputeClient::ProjectsApi
    VersionApi = ::ComputeClient::VersionApi
    VirtualDisksApi = ::ComputeClient::VirtualDisksApi
    VirtualNetworksApi = ::ComputeClient::VirtualNetworksApi
    
    # Re-export all model classes
    ApiVersion = ::ComputeClient::ApiVersion
    ApiVersionResponse = ::ComputeClient::ApiVersionResponse
    Catlet = ::ComputeClient::Catlet
    CatletConfigValidationResult = ::ComputeClient::CatletConfigValidationResult
    CatletConfiguration = ::ComputeClient::CatletConfiguration
    CatletDrive = ::ComputeClient::CatletDrive
    CatletDriveType = ::ComputeClient::CatletDriveType
    CatletList = ::ComputeClient::CatletList
    CatletNetwork = ::ComputeClient::CatletNetwork
    CatletNetworkAdapter = ::ComputeClient::CatletNetworkAdapter
    CatletStatus = ::ComputeClient::CatletStatus
    CatletStopMode = ::ComputeClient::CatletStopMode
    DiskStatus = ::ComputeClient::DiskStatus
    ExpandCatletConfigRequestBody = ::ComputeClient::ExpandCatletConfigRequestBody
    ExpandNewCatletConfigRequest = ::ComputeClient::ExpandNewCatletConfigRequest
    FloatingNetworkPort = ::ComputeClient::FloatingNetworkPort
    Gene = ::ComputeClient::Gene
    GeneList = ::ComputeClient::GeneList
    GeneType = ::ComputeClient::GeneType
    GeneWithUsage = ::ComputeClient::GeneWithUsage
    NewCatletRequest = ::ComputeClient::NewCatletRequest
    NewProjectMemberBody = ::ComputeClient::NewProjectMemberBody
    NewProjectRequest = ::ComputeClient::NewProjectRequest
    NewVirtualDiskRequest = ::ComputeClient::NewVirtualDiskRequest
    Operation = ::ComputeClient::Operation
    OperationList = ::ComputeClient::OperationList
    OperationLogEntry = ::ComputeClient::OperationLogEntry
    OperationResource = ::ComputeClient::OperationResource
    OperationResult = ::ComputeClient::OperationResult
    OperationStatus = ::ComputeClient::OperationStatus
    OperationTask = ::ComputeClient::OperationTask
    OperationTaskReference = ::ComputeClient::OperationTaskReference
    OperationTaskStatus = ::ComputeClient::OperationTaskStatus
    PopulateCatletConfigVariablesRequest = ::ComputeClient::PopulateCatletConfigVariablesRequest
    ProblemDetails = ::ComputeClient::ProblemDetails
    Project = ::ComputeClient::Project
    ProjectList = ::ComputeClient::ProjectList
    ProjectMemberRole = ::ComputeClient::ProjectMemberRole
    ProjectMemberRoleList = ::ComputeClient::ProjectMemberRoleList
    ResourceType = ::ComputeClient::ResourceType
    StopCatletRequestBody = ::ComputeClient::StopCatletRequestBody
    TaskReferenceType = ::ComputeClient::TaskReferenceType
    UpdateCatletRequestBody = ::ComputeClient::UpdateCatletRequestBody
    UpdateProjectNetworksRequestBody = ::ComputeClient::UpdateProjectNetworksRequestBody
    ValidateConfigRequest = ::ComputeClient::ValidateConfigRequest
    ValidationIssue = ::ComputeClient::ValidationIssue
    VirtualDisk = ::ComputeClient::VirtualDisk
    VirtualDiskAttachedCatlet = ::ComputeClient::VirtualDiskAttachedCatlet
    VirtualDiskGeneInfo = ::ComputeClient::VirtualDiskGeneInfo
    VirtualDiskList = ::ComputeClient::VirtualDiskList
    VirtualNetwork = ::ComputeClient::VirtualNetwork
    VirtualNetworkConfiguration = ::ComputeClient::VirtualNetworkConfiguration
    VirtualNetworkList = ::ComputeClient::VirtualNetworkList
    CatletConfigOperationResult = ::ComputeClient::CatletConfigOperationResult
  end
  
  # Keep the old Generated namespace for backward compatibility
  module Generated
    # Alias the main classes for backward compatibility
    NewCatletRequest = ::ComputeClient::NewCatletRequest
    StopCatletRequestBody = ::ComputeClient::StopCatletRequestBody
    CatletStopMode = ::ComputeClient::CatletStopMode
    ApiClient = ::ComputeClient::ApiClient
    Configuration = ::ComputeClient::Configuration
  end
  
  module Compute
    module Generated
      # Re-export the generated client classes for easier access
      Client = ::ComputeClient
    end
  end
end